openapi: 3.0.3
info:
  title: Job Portal API
  version: 1.0.0
  description: API documentation for the Job Portal backend
paths:
  /api/accounts/company-profile/:
    get:
      operationId: api_accounts_company_profile_retrieve
      tags:
      - Profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
  /api/accounts/jobseeker-profile/:
    get:
      operationId: api_accounts_jobseeker_profile_retrieve
      tags:
      - Profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobSeeker'
          description: ''
  /api/accounts/login/:
    post:
      operationId: api_accounts_login_create
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLogin'
          description: ''
  /api/accounts/logout/:
    post:
      operationId: api_accounts_logout_create
      tags:
      - Auth
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                message: Logged out successfully
          description: ''
  /api/accounts/profile/:
    get:
      operationId: api_accounts_profile_retrieve
      tags:
      - Profile
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/accounts/register/:
    post:
      operationId: api_accounts_register_create
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/jobs/:
    get:
      operationId: api_jobs_list
      description: Returns a paginated list of all jobs, ordered by newest first.
      summary: List all job posts
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Jobs
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedJobList'
          description: ''
  /api/jobs/{id}/:
    get:
      operationId: api_jobs_retrieve
      description: Retrieve a job post or update/delete it. Only the company who created
        the job can modify it.
      summary: Retrieve, update, or delete a job
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Jobs
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
    put:
      operationId: api_jobs_update
      description: Retrieve a job post or update/delete it. Only the company who created
        the job can modify it.
      summary: Retrieve, update, or delete a job
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JobRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JobRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
    patch:
      operationId: api_jobs_partial_update
      description: Retrieve a job post or update/delete it. Only the company who created
        the job can modify it.
      summary: Retrieve, update, or delete a job
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedJobRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedJobRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedJobRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
    delete:
      operationId: api_jobs_destroy
      description: Retrieve a job post or update/delete it. Only the company who created
        the job can modify it.
      summary: Retrieve, update, or delete a job
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Jobs
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
  /api/jobs/applications/:
    get:
      operationId: api_jobs_applications_list
      description: Company users can view all applications submitted to their job
        posts.
      summary: List job applications
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - Applications
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedApplicationList'
          description: ''
  /api/jobs/apply/:
    post:
      operationId: api_jobs_apply_create
      description: Only job seekers can apply for jobs.
      summary: Apply to a job
      tags:
      - Applications
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ApplicationRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: ''
  /api/jobs/create/:
    post:
      operationId: api_jobs_create_create
      description: Only company users can create job posts.
      summary: Create a new job post
      tags:
      - Jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JobRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JobRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
          description: ''
components:
  schemas:
    Application:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        cover_letter:
          type: string
        applied_at:
          type: string
          format: date-time
          readOnly: true
        status:
          type: string
          maxLength: 50
        job:
          type: integer
        jobseeker:
          type: integer
      required:
      - applied_at
      - cover_letter
      - id
      - job
      - jobseeker
    ApplicationRequest:
      type: object
      properties:
        cover_letter:
          type: string
          minLength: 1
        status:
          type: string
          minLength: 1
          maxLength: 50
        job:
          type: integer
        jobseeker:
          type: integer
      required:
      - cover_letter
      - job
      - jobseeker
    Company:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        company_name:
          type: string
          maxLength: 255
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
      required:
      - company_name
      - id
      - user
    Job:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        salary:
          type: string
          maxLength: 100
        location:
          type: string
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
        company:
          type: integer
      required:
      - company
      - created_at
      - description
      - id
      - location
      - salary
      - title
    JobRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          minLength: 1
        salary:
          type: string
          minLength: 1
          maxLength: 100
        location:
          type: string
          minLength: 1
          maxLength: 255
        company:
          type: integer
      required:
      - company
      - description
      - location
      - salary
      - title
    JobSeeker:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        resume:
          type: string
          format: uri
          nullable: true
        bio:
          type: string
          nullable: true
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
      required:
      - id
      - user
    PaginatedApplicationList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Application'
    PaginatedJobList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Job'
    PatchedJobRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          minLength: 1
        salary:
          type: string
          minLength: 1
          maxLength: 100
        location:
          type: string
          minLength: 1
          maxLength: 255
        company:
          type: integer
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        user_type:
          $ref: '#/components/schemas/UserTypeEnum'
      required:
      - email
      - id
      - user_type
      - username
    UserLogin:
      type: object
      properties:
        username:
          type: string
        token:
          type: object
          additionalProperties: {}
          readOnly: true
        user_type:
          type: string
          readOnly: true
      required:
      - token
      - user_type
      - username
    UserLoginRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - password
      - username
    UserRegistrationRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          minLength: 1
          maxLength: 254
        password:
          type: string
          writeOnly: true
          minLength: 1
        user_type:
          $ref: '#/components/schemas/UserTypeEnum'
      required:
      - email
      - password
      - user_type
      - username
    UserTypeEnum:
      enum:
      - company
      - jobseeker
      type: string
      description: |-
        * `company` - Company
        * `jobseeker` - Job Seeker
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
