# Generated by Django 6.0 on 2025-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
